Fix some bugs
huggingface/nanotron pull request #100
Opened 2024-03-11 15:05 UTC by jordane95

* Now dp should be the third dimension of parallel ranks
* One missing argument

2024-03-12 12:14 UTC, xrsrke requested changes

2024-03-12 12:14 UTC, xrsrke commented on src/nanotron/serialize/weights.py
> +                is_expert_sharded = False
why do we put is_expert_sharded = False? would be cool if we put some notes here

2024-03-12 13:39 UTC, xrsrke requested changes
> Now dp should be the third dimension of parallel ranks
Could you please elaborate on this?

> One missing argument
Where is it 🤔

2024-03-12 16:04 UTC, jordane95 commented
> > Now dp should be the third dimension of parallel ranks
> 
> Could you please elaborate on this?
> 
> > One missing argument
> 
> Where is it 🤔

1. It is quite straightforward by looking at the definition of rank matrix
https://github.com/huggingface/nanotron/blob/ff3c7746577948743da08c4868aca46cbc0c110b/src/nanotron/parallel/context.py#L69-L76

2. Missing `is_expert_sharded` variable would cause referenced before defined error

https://github.com/huggingface/nanotron/blob/ff3c7746577948743da08c4868aca46cbc0c110b/src/nanotron/serialize/weights.py#L72-L95

2024-03-14 10:21 UTC, NouamaneTazi approved these changes
LGTM! it's part of my series of expert parallelism fixes. Some fixes made it in a previous PR. Thanks for noticing!

2024-03-14 10:21 UTC, merged