[Docs] Add unit tests as a requirement
huggingface/nanotron pull request #93
Opened 2024-03-03 13:27 UTC by xrsrke

2024-03-04 03:08 UTC, xrsrke commented
@3outeille @NouamaneTazi wdyt?

2024-03-04 09:41 UTC, NouamaneTazi requested changes

2024-03-04 09:41 UTC, NouamaneTazi commented on README.md
> +We have extensions built on top of Nanotron, with their tests located in the `/examples` folder. Since VSCode defaults to discovering tests only in the `/tests` folder, please run tests from both `/e
maybe add command we should run to test both folders

2024-03-25 11:57 UTC, NouamaneTazi approved these changes
LGTM!

2024-03-25 11:57 UTC, merged